export const MATCHING_CONSTANTS = {
  FREE_DAILY_ACTIVITIES: 1,
  PLUS_DAILY_ACTIVITIES: 3,
  FREE_DAILY_MATCH_ACCEPTS: 3,
  PLUS_DAILY_MATCH_ACCEPTS: 10,
  MATCH_REQUEST_EXPIRES_MINUTES: 10,
  ACTIVITY_EXPIRES_HOURS: 2,
} as const;
