export const TIMER_CONSTANTS = {
  DEFAULT_DURATION_SECONDS: 30 * 60,
  PLUS_DURATION_SECONDS: 45 * 60,
  WARNING_THRESHOLD_SECONDS: 5 * 60,
  URGENT_THRESHOLD_SECONDS: 60,
  EXTENSION_SECONDS: 15 * 60,
} as const;
